In [1]:
import numpy as np


In [3]:
a = np.array([12,12,7.8,56])
print(a)

[12.  12.   7.8 56. ]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
print(a.dtype)

float64


In [6]:
print(a.ndim)

1


In [8]:
print(a.shape)


(4,)


In [12]:
b = np.array([[52,45,96],[89,87,86]])
print(b)

[[52 45 96]
 [89 87 86]]


In [14]:
c = np.array([[25,70,62],[43,15,63]])
print(c)

[[25 70 62]
 [43 15 63]]


In [15]:
print(c+b)

[[ 77 115 158]
 [132 102 149]]


In [16]:
print(b*c)

[[1300 3150 5952]
 [3827 1305 5418]]


In [18]:
print(np.mean(b))

75.83333333333333


In [19]:
print(np.mean(c))

46.333333333333336


In [20]:
x=np.array([10,20,30])
y=np.array([11,12,13])
z=np.array([21,22,23])

In [22]:
print(np.vstack((x,y,z)))

[[10 20 30]
 [11 12 13]
 [21 22 23]]


In [25]:
print(np.hstack((x,y,z)))

[10 20 30 11 12 13 21 22 23]


In [26]:
print(np.flip(b*c))

[[5418 1305 3827]
 [5952 3150 1300]]
