In [2]:
import numpy as np

In [3]:
# Write a NumPy program to get the numpy version and show numpy build configuration.
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Rohit/anaconda3/Library/include
    lib directory: C:/Users/Rohit/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1868282989520
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
  

In [4]:
# Write a NumPy program to get help on the add function
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [5]:
# Write a NumPy program to test whether none of the elements of a given array is zero.
a = np.array([1,23,4,5,7,8])
print(np.all(a))

True


In [6]:
# Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).
a = np.array([1,2,5,4,np.inf,np.nan])
print(np.isfinite(a))

[ True  True  True  True False False]


In [7]:
# Write a NumPy program to test element-wise for positive or negative infinity.
print(np.isinf(a))

[False False False False  True False]


In [8]:
# Write a NumPy program to test element-wise for NaN of a given array.
print(np.isnan(a))

[False False False False False  True]


In [9]:
# Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.
b = np.array([2+2j,1+1j,8,5+6j,8.5])
print(np.iscomplex(b))
print(np.isreal(b))
print(np.isscalar(8.5))

[ True  True False  True False]
[False False  True False  True]
True


In [10]:
# Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.
a = np.array([1,2,3])
b = np.array([3,4,5])
print("Equal",a == b)
print("greater:",a > b)
print("greater_equal",a >= b)
print("less",a < b)
print("less_equal",a <= b)

Equal [False False False]
greater: [False False False]
greater_equal [False False False]
less [ True  True  True]
less_equal [ True  True  True]


In [11]:
# Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.
a= np.array([1, 7, 13, 105])
print((a.size * a.itemsize))


16


In [12]:
# Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.
a = np.zeros(10)
print(a)
b = np.ones(10)
print(b)
c = np.ones(10) *5
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [13]:
# Write a NumPy program to create an array of integers from 30 to70.
a = np.arange(30,70)
print(a)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [14]:
# Write a NumPy program to create an array of all the even integers from 30 to 70.
a = np.arange(30,70,2)
print(a)
            

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


In [15]:
# Write a NumPy program to create a 3x3 identity matrix.
print(np.identity(3))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# Write a NumPy program to generate a random number between 0 and 1.
print(np.random.randint(0,1))

0


In [17]:
# Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.
print(np.random.randn(15))

[ 0.39523276 -0.13709899  0.83466888  0.06792326 -0.31513328  0.40508859
  0.87020424 -0.87697976 -0.95754434 -0.83347783  1.1686072   1.69842991
 -0.3886535   0.13791361  0.24655047]


In [18]:
# Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.
a = np.arange(15,55)
print(a[1:])


[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [19]:
# Write a NumPy program to create a 3X4 array using and iterate over it.
arr = np.array(([5,10,15,5],[20,25,30,54],[35,40,45,54]))

# iterate it;
for i in np.nditer(arr):
    print(i,end=" ")

5 10 15 5 20 25 30 54 35 40 45 54 

In [20]:
# Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.
a = np.linspace(5,50,10)
print(a)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [21]:
# Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.
a = np.arange(0,20)
a[(a>=9) & (a<=15)] *= -1 

print(a)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19]


In [22]:
# Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.
print(np.random.randint(0,10,5))

[7 9 7 9 9]


In [23]:
# Write a NumPy program to multiply the values of two given vectors
a = np.array([0,5,5,8,2])
b = np.array([0,6,5,8,2])
print(a*b)

[ 0 30 25 64  4]


In [24]:
# Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.
print(np.arange(10,22).reshape((3,4)))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [25]:
# Write a NumPy program to find the number of rows and columns of a given matrix.
arr = np.array([[1,2,3,4],[5,6,7,8],[9,8,7,6],[5,4,3,2],[1,9,8,2]])
print(arr.shape)

(5, 4)


In [26]:
# Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0.
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
# Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.
a = np.ones((10,10))
a[1:-1,1:-1] =0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [28]:
# Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1,2, 3, 4, 5.
a = np.diag([1,2,3,4,5])
print(a)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [29]:
# Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.
a = np.zeros((4,4))
a[::2,1::2]=1
a[1::2,::2]=1
print(a)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [30]:
# Write a NumPy program to create a 3x3x3 array filled with arbitrary values.
a = np.random.random((3,3,3))
print(a)

[[[0.48438483 0.93710276 0.3842164 ]
  [0.63698633 0.07855047 0.77248183]
  [0.27084105 0.77287197 0.27632558]]

 [[0.62855729 0.37206683 0.46727047]
  [0.31606716 0.72927208 0.57890979]
  [0.68048199 0.67768782 0.1575703 ]]

 [[0.9773823  0.97765364 0.747475  ]
  [0.31309443 0.37020455 0.04833939]
  [0.53205757 0.32818974 0.94680317]]]


In [31]:
# Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.
x = np.array([[1,2],[3,4],[4,5]])
print(x)
print("sum is",np.sum(x))
print("col sum is",np.sum(x,axis=0))
print("row sum is",np.sum(x,axis=1))

[[1 2]
 [3 4]
 [4 5]]
sum is 19
col sum is [ 8 11]
row sum is [3 7 9]


In [32]:
# Write a NumPy program to compute the inner product of two given vectors.
a=np.array([1,2])
b=np.array([4,6])
print("The product is: ",np.dot(a,b))

The product is:  16


In [33]:
# Write a NumPy program to add a vector to each row of a given matrix.
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([4,8,6])

# Creating an empty matrix 'result' with the same shape as 'm' using np.empty_like()
result = np.empty_like(a)
# add:
for i in range(4):
    result[i,] = a[i,:] + v 
print(result)


[[ 5 10  9]
 [ 8 13 12]
 [11 16 15]
 [14 19 18]]


In [49]:
# Write a NumPy program to convert numpy dtypes to native python types.

x = np.float32(0)
print(type(x))

pyval = x.item()
print(type(pyval)) 



<class 'numpy.float32'>
<class 'float'>


In [35]:
# Write a NumPy program to find the missing data in a given array.
print(np.isnan(a))

[[False False False]
 [False False False]
 [False False False]
 [False False False]]


In [36]:
# Write a NumPy program to sort a given array by row and column in ascending order.
a = np.array([4,8,9,1])
print(np.sort(a))
print(np.sort(a,axis=0))
            

[1 4 8 9]
[1 4 8 9]


In [40]:
# Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.

nums = np.array([[5.54, 3.38, 7.99],
              [3.54, 4.38, 6.99],
              [1.54, 2.39, 9.29]])
n = 5
print("\nElements of the said array greater than", n)
print(nums[nums > n])

n = 6
print("\nElements of the said array less than", n)
print(nums[nums < n]) 



Elements of the said array greater than 5
[5.54 7.99 6.99 9.29]

Elements of the said array less than 6
[5.54 3.38 3.54 4.38 1.54 2.39]


In [122]:
# Write a NumPy program to replace all numbers in a given array which is equal, less and greater to a given number.
a = np.array([1,4,9])
v = 4
k = 7

print(np.where(a == v, k, a))
print(np.where(a < v, k, a))
print(np.where(a>v,k,a))
        


[1 7 9]
[7 4 9]
[1 4 7]


In [83]:
# Write a NumPy program to create a three-dimensional array with shapes (3,5,4) and set to a variable.
arr = np.array([[[1,2,3,4],[5,6,7,8],[9,8,7,6],[5,4,3,2],[1,9,8,2]],
                [[2,3,4,7],[8,6,5,3],[7,1,9,5],[3,6,8,3],[7,9,5,7]],
                [[7,4,8,2],[8,7,8,4],[2,4,5,9],[9,5,7,3],[2,5,8,8]]])

print(arr)

[[[1 2 3 4]
  [5 6 7 8]
  [9 8 7 6]
  [5 4 3 2]
  [1 9 8 2]]

 [[2 3 4 7]
  [8 6 5 3]
  [7 1 9 5]
  [3 6 8 3]
  [7 9 5 7]]

 [[7 4 8 2]
  [8 7 8 4]
  [2 4 5 9]
  [9 5 7 3]
  [2 5 8 8]]]


In [79]:
# Write a NumPy program to multiply two given arrays of same size element-by-element.
arr9 = np.array([25,45,86])
arr10 = np.array([9,7,2])
mul = arr9 * arr10
print(mul)

[225 315 172]
